Repository DevenRathod2/appwrite-star-counter, pull requests merged in 2022-10, with the labels that each got.

#2 Fixed Some UI Issues
  pages/index.jsx
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#3 Code Optimisation
  README.md
  pages/index.jsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#4 Fixed Mobile Responsive Bug
  pages/index.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#1 contributer name added
  CONTRIBUTING.md
  package-lock.json
  styles/Home.module.css
  yarn.lock
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted
